services:
  postgresql:
    container_name: postgresql
    build: database
    environment:
      POSTGRES_DB: projectmanager
      POSTGRES_USER: monre
      POSTGRES_PASSWORD: Monre123!
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - projectManager

  backend:
    container_name: backend
    build: backend
    command: "tail -f /dev/null"
    # command: >
    #   sh -c "sleep 15 &&
    #         python manage.py migrate &&
    #         python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgresql
    networks:
      - projectManager

  frontend:
    container_name: frontend
    image: httpd:2.4
    restart: unless-stopped
    volumes:
      - ./frontend:/usr/local/apache2/htdocs:ro
    networks:
      - projectManager

  nginx-proxy:
    container_name: nginx-proxy
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - projectManager

volumes:
  postgres_data:


networks:
  projectManager:
    driver: bridge
